name: HomeGPT
slug: homegpt
description: "Streams HA events to OpenAI; summarizes (passive) or controls (active) with allow-lists and rate limits."
url: https://github.com/Prosono/HomeGPT
startup: application
init: false
image: ghcr.io/prosono/homegpt
version: "0.1.1"
arch:
  - amd64
  - aarch64
  - armv7
homeassistant_api: true
map:
  - config:rw

# Ingress settings
ingress: true
ingress_port: 8099
panel_icon: mdi:robot
panel_title: HomeGPT

# Default options
options:
  openai_api_key: ""
  model: "gpt-5"
  mode: "passive"
  summarize_time: "21:30"
  control_allowlist: []
  max_actions_per_hour: 10
  dry_run: true
  log_level: INFO
  language: "en"

# User input schema
schema:
  openai_api_key: str
  model: str
  mode: list(passive|active)
  summarize_time: str
  control_allowlist: [str]
  max_actions_per_hour: int
  dry_run: bool
  log_level: list(DEBUG|INFO|WARNING|ERROR)
  language: str
