name: HomeGPT
slug: homegpt
version: "0.1.0"
description: "Streams HA events to OpenAI; summarizes (passive) or controls (active) with allow‑lists and rate limits."
url: https://example.com/homegpt-docs
startup: application
init: false
arch:
  - amd64
  - aarch64
  - armv7
homeassistant_api: true  # gives SUPERVISOR_TOKEN + internal API access
map:
  - config:rw            # optional if you want to read HA config
options:
  openai_api_key: ""
  model: "gpt-4o-mini"
  mode: "passive"          # passive | active
  summarize_time: "12:45"  # local HA time (HH:MM)
  control_allowlist: []     # list of entity_ids allowed to be controlled in active mode
  max_actions_per_hour: 10
  dry_run: true             # if true, only propose actions and create notifications
  log_level: INFO
  language: "en"            # "en", "no", etc. Used in prompts/notifications
schema:
  openai_api_key: str
  model: str
  mode: list(passive|active)
  summarize_time: str
  control_allowlist: [str]
  max_actions_per_hour: int
  dry_run: bool
  log_level: list(DEBUG|INFO|WARNING|ERROR)
  language: str