name: HomeGPT
slug: homegpt
version: "0.1.0"
description: "Streams HA events to OpenAI; summarizes (passive) or controls (active) with allow-lists and rate limits."
url: https://github.com/prosono/homegpt
startup: application
init: false
image: "ghcr.io/prosono/homegpt:0.1.0"
arch:
  - amd64
  - aarch64
  - armv7
homeassistant_api: true
map:
  - config:rw
options:
  openai_api_key: ""
  model: "gpt-4o-mini"
  mode: "passive"
  summarize_time: "21:30"
  control_allowlist: []
  max_actions_per_hour: 10
  dry_run: true
  log_level: INFO
  language: "en"
schema:
  openai_api_key: str
  model: str
  mode: list(passive|active)
  summarize_time: str
  control_allowlist: [str]
  max_actions_per_hour: int
  dry_run: bool
  log_level: list(DEBUG|INFO|WARNING|ERROR)
  language: str